// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {p2p} from '../models';

export function AddDeviceByIP(arg1:string,arg2:string):Promise<models.Device>;

export function ChooseDownloadDir():Promise<string>;

export function ConnectP2P(arg1:string,arg2:string):Promise<void>;

export function CreateGroup(arg1:string):Promise<models.Group>;

export function DisconnectP2P(arg1:string):Promise<void>;

export function DownloadSharedFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDevices():Promise<Array<models.Device>>;

export function GetDownloadDir():Promise<string>;

export function GetGroupInvite(arg1:string):Promise<string>;

export function GetGroups():Promise<Array<models.Group>>;

export function GetHistory():Promise<Array<models.TransferRecord>>;

export function GetLocalDevice():Promise<models.Device>;

export function GetMessages():Promise<Array<models.Message>>;

export function GetP2PStatus():Promise<Record<string, any>>;

export function GetPairedPeers():Promise<Array<main.PairedPeer>>;

export function GetSettings():Promise<main.AppSettings>;

export function GoOffline():Promise<void>;

export function GoOnline():Promise<void>;

export function IsOnline():Promise<boolean>;

export function JoinGroup(arg1:string):Promise<models.Group>;

export function LeaveGroup(arg1:string):Promise<void>;

export function OpenDownloadFolder():Promise<void>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenFileInFolder(arg1:string):Promise<string>;

export function PingDevice(arg1:string):Promise<string>;

export function RefreshDevices():Promise<Array<models.Device>>;

export function RemoveKnownDevice(arg1:string):Promise<void>;

export function RemoveManualDevice(arg1:string):Promise<void>;

export function RespondTransfer(arg1:string,arg2:boolean):Promise<void>;

export function SendFile(arg1:string,arg2:string,arg3:string):Promise<models.TransferRecord>;

export function SendFilePath(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.TransferRecord>;

export function SendGroupFile(arg1:string):Promise<Array<models.TransferRecord>>;

export function SendGroupFilePath(arg1:string,arg2:string):Promise<Array<models.TransferRecord>>;

export function SendGroupMessage(arg1:string,arg2:string):Promise<models.Message>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Message>;

export function SendMultipleFiles(arg1:string,arg2:string,arg3:string):Promise<Array<models.TransferRecord>>;

export function SendP2PFile(arg1:string):Promise<models.TransferRecord>;

export function SendP2PFilePath(arg1:string,arg2:string):Promise<models.TransferRecord>;

export function SendP2PMessage(arg1:string,arg2:string):Promise<models.Message>;

export function SetAskSaveLocation(arg1:boolean):Promise<void>;

export function SetDisplayName(arg1:string):Promise<void>;

export function SetDownloadDir(arg1:string):Promise<string>;

export function ShareFile(arg1:string,arg2:string,arg3:string):Promise<models.SharedFile>;

export function ShareFilePath(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.SharedFile>;

export function ShareGroupFile(arg1:string):Promise<Array<models.SharedFile>>;

export function ShareGroupFilePath(arg1:string,arg2:string):Promise<Array<models.SharedFile>>;

export function StartP2P():Promise<p2p.UPnPResult>;

export function StartPairing(arg1:string):Promise<void>;

export function StopP2P():Promise<void>;

export function Unpair(arg1:string):Promise<void>;
