// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeviceByIP(arg1, arg2) {
  return window['go']['main']['App']['AddDeviceByIP'](arg1, arg2);
}

export function ChooseDownloadDir() {
  return window['go']['main']['App']['ChooseDownloadDir']();
}

export function ConnectP2P(arg1, arg2) {
  return window['go']['main']['App']['ConnectP2P'](arg1, arg2);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DisconnectP2P(arg1) {
  return window['go']['main']['App']['DisconnectP2P'](arg1);
}

export function DownloadSharedFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSharedFile'](arg1, arg2, arg3);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GetGroupInvite(arg1) {
  return window['go']['main']['App']['GetGroupInvite'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLocalDevice() {
  return window['go']['main']['App']['GetLocalDevice']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function GetPairedPeers() {
  return window['go']['main']['App']['GetPairedPeers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GoOffline() {
  return window['go']['main']['App']['GoOffline']();
}

export function GoOnline() {
  return window['go']['main']['App']['GoOnline']();
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function JoinGroup(arg1) {
  return window['go']['main']['App']['JoinGroup'](arg1);
}

export function LeaveGroup(arg1) {
  return window['go']['main']['App']['LeaveGroup'](arg1);
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileInFolder(arg1) {
  return window['go']['main']['App']['OpenFileInFolder'](arg1);
}

export function PingDevice(arg1) {
  return window['go']['main']['App']['PingDevice'](arg1);
}

export function RefreshDevices() {
  return window['go']['main']['App']['RefreshDevices']();
}

export function RemoveKnownDevice(arg1) {
  return window['go']['main']['App']['RemoveKnownDevice'](arg1);
}

export function RemoveManualDevice(arg1) {
  return window['go']['main']['App']['RemoveManualDevice'](arg1);
}

export function RespondTransfer(arg1, arg2) {
  return window['go']['main']['App']['RespondTransfer'](arg1, arg2);
}

export function SendFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3);
}

export function SendFilePath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFilePath'](arg1, arg2, arg3, arg4);
}

export function SendGroupFile(arg1) {
  return window['go']['main']['App']['SendGroupFile'](arg1);
}

export function SendGroupFilePath(arg1, arg2) {
  return window['go']['main']['App']['SendGroupFilePath'](arg1, arg2);
}

export function SendGroupMessage(arg1, arg2) {
  return window['go']['main']['App']['SendGroupMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMultipleFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMultipleFiles'](arg1, arg2, arg3);
}

export function SendP2PFile(arg1) {
  return window['go']['main']['App']['SendP2PFile'](arg1);
}

export function SendP2PFilePath(arg1, arg2) {
  return window['go']['main']['App']['SendP2PFilePath'](arg1, arg2);
}

export function SendP2PMessage(arg1, arg2) {
  return window['go']['main']['App']['SendP2PMessage'](arg1, arg2);
}

export function SetAskSaveLocation(arg1) {
  return window['go']['main']['App']['SetAskSaveLocation'](arg1);
}

export function SetCustomRelays(arg1) {
  return window['go']['main']['App']['SetCustomRelays'](arg1);
}

export function SetDisplayName(arg1) {
  return window['go']['main']['App']['SetDisplayName'](arg1);
}

export function SetDownloadDir(arg1) {
  return window['go']['main']['App']['SetDownloadDir'](arg1);
}

export function SetTransportMode(arg1) {
  return window['go']['main']['App']['SetTransportMode'](arg1);
}

export function SetUseDoH(arg1) {
  return window['go']['main']['App']['SetUseDoH'](arg1);
}

export function ShareFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShareFile'](arg1, arg2, arg3);
}

export function ShareFilePath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ShareFilePath'](arg1, arg2, arg3, arg4);
}

export function ShareGroupFile(arg1) {
  return window['go']['main']['App']['ShareGroupFile'](arg1);
}

export function ShareGroupFilePath(arg1, arg2) {
  return window['go']['main']['App']['ShareGroupFilePath'](arg1, arg2);
}

export function StartP2P() {
  return window['go']['main']['App']['StartP2P']();
}

export function StartPairing(arg1) {
  return window['go']['main']['App']['StartPairing'](arg1);
}

export function StopP2P() {
  return window['go']['main']['App']['StopP2P']();
}

export function Unpair(arg1) {
  return window['go']['main']['App']['Unpair'](arg1);
}
